-- CreateTable
CREATE TABLE "Order" (
    "OrderID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "PenjualanID" INTEGER NOT NULL,
    "ProdukID" INTEGER NOT NULL,
    "JumlahProduk" INTEGER NOT NULL,
    "Subtotal" DECIMAL NOT NULL DEFAULT 0.0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Order_PenjualanID_fkey" FOREIGN KEY ("PenjualanID") REFERENCES "Penjualan" ("PenjualanID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Order_ProdukID_fkey" FOREIGN KEY ("ProdukID") REFERENCES "Produk" ("ProdukID") ON DELETE RESTRICT ON UPDATE CASCADE
);
